version: '3.8'

services:
  eureka:
    image: steeltoeoss/eureka-server:latest
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_ADDRESS=http://eureka:8761/eureka/
      - eureka.client.registerWithEureka=false
      - eureka.client.fetchRegistry=false
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  attendance-service:
    build:
      context: ./Attendance_service
      dockerfile: Dockerfile.attendanceserver
    expose:
      - 8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://attendance-db:5432/${ATTENDANCE_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_APPLICATION_NAME=attendance_service
      - SERVER_PORT=8081
      - EUREKA_CLIENT_REGISTERWITHEUREKA=true
      - EUREKA_CLIENT_FETCHREGISTRY=true
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    depends_on:
      eureka:
        condition: service_started
      attendance-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 120s
      timeout: 60s
      retries: 5
      start_period: 60s
    networks:
      - app-network

  auth-service:
    build:
      context: ./Auth_Service
      dockerfile: Dockerfile.authserver
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/${AUTH_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_APPLICATION_NAME=auth_service
      - SERVER_PORT=8080
      - EUREKA_CLIENT_REGISTERWITHEUREKA=true
      - EUREKA_CLIENT_FETCHREGISTRY=true
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    depends_on:
      eureka:
        condition: service_started
      auth-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 120s
      timeout: 60s
      retries: 5
      start_period: 60s
    networks:
      - app-network

  user-service:
    build:
      context: ./User_service
      dockerfile: Dockerfile.userserver
    expose:
      - 8084
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/${USER_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_APPLICATION_NAME=user_service
      - SERVER_PORT=8084
      - EUREKA_CLIENT_REGISTERWITHEUREKA=true
      - EUREKA_CLIENT_FETCHREGISTRY=true
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    depends_on:
      eureka:
        condition: service_started
      user-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 120s
      timeout: 60s
      retries: 5
      start_period: 60s
    networks:
      - app-network

  payroll-service:
    build:
      context: ./Payroll_service
      dockerfile: Dockerfile.payrollserver
    expose:
      - 8082
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payroll-db:5432/${PAYROLL_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_APPLICATION_NAME=payroll_service
      - SERVER_PORT=8082
      - EUREKA_CLIENT_REGISTERWITHEUREKA=true
      - EUREKA_CLIENT_FETCHREGISTRY=true
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    depends_on:
      eureka:
        condition: service_started
      payroll-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 120s
      timeout: 60s
      retries: 5
      start_period: 60s
    restart: always
    networks:
      - app-network

  attendance-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${ATTENDANCE_DB_NAME}
    volumes:
      - attendance-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  auth-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${AUTH_DB_NAME}
    volumes:
      - auth-data:/var/lib/postgresql/data
      - ./Auth_Service/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  user-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${USER_DB_NAME}
    volumes:
      - user-data:/var/lib/postgresql/data
      - ./User_service/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  payroll-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${PAYROLL_DB_NAME}
    volumes:
      - payroll-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  api-gateway:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - attendance-service
      - user-service
      - payroll-service
      - eureka
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 90s
      timeout: 30s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  attendance-data:
  auth-data:
  user-data:
  payroll-data: