version: '3.8'

services:
  auth_db_postgres:
    image: postgres:15
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8086:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.authserver
    container_name: auth-service
    depends_on:
      - auth_db_postgres
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth_db_postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}