version: '3.8'

services:
  user_db_postgres:
    image: postgres:15
    container_name: user-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8087:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - shared-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile.userserver
    container_name: user-service
    depends_on:
      - user_db_postgres
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user_db_postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - shared-network

networks:
  shared-network:
    external: true