version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: payroll_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth=scram-sha-256 --username=${POSTGRES_USER}"

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  payroll-service:
    build:
      context: .
      dockerfile: Dockerfile.payrollserver
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

volumes:
  postgres_data:
